# -*- coding: utf-8 -*-
"""NLTK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14h9xzH5rkuHi40cIL_Crb2ARVHaDBJxa
"""

!pip install nltk

import nltk
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

from nltk.corpus import wordnet

def informal_to_formal(informal_sentence):
    tokens = nltk.word_tokenize(informal_sentence)
    tagged_tokens = nltk.pos_tag(tokens)
    formal_sentence = ""

    for token, tag in tagged_tokens:
        if tag.startswith('V'):
            lemma = wordnet.morphy(token, wordnet.VERB)
            if lemma is None:
                formal_sentence += " " + token
            else:
                formal_sentence += " " + lemma[0]
        elif tag.startswith('N'):
            lemma = wordnet.morphy(token, wordnet.NOUN)
            if lemma is None:
                formal_sentence += " " + token
            else:
                formal_sentence += " " + lemma[0]
        elif tag.startswith('J'):
            lemma = wordnet.morphy(token, wordnet.ADJ)
            if lemma is None:
                formal_sentence += " " + token
            else:
                formal_sentence += " " + lemma[0]
        elif tag.startswith('R'):
            lemma = wordnet.morphy(token, wordnet.ADV)
            if lemma is None:
                formal_sentence += " " + token
            else:
                formal_sentence += " " + lemma[0]
        elif tag.startswith('W'):
            formal_sentence += " " + token.capitalize()
        elif token == "gonna":
            formal_sentence += " going to"
        elif token == "wanna":
            formal_sentence += " want to"
        else:
            formal_sentence += " " + token

    formal_sentence = formal_sentence.strip()
    formal_sentence = formal_sentence[0].upper() + formal_sentence[1:] + "."

    return formal_sentence

informal_sentence = "hey wassup dude im gonna go to the store cuz i wanna get some snacks"
formal_sentence = informal_to_formal(informal_sentence)
print("Informal sentence:", informal_sentence)
print("Formal sentence:", formal_sentence)